--USER 생성

DROP USER C##USER1;
CREATE USER C##USER1 IDENTIFIED BY pw123;

-- USER1에게 기본적인 접근 권한과 객체 생성 권한 부여
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO C##USER1;

-- USER1로부터 CREATE VIEW 권한 회수
REVOKE CREATE VIEW FROM C##USER1;

-- ALTER USER : 사용자 암호 변경
ALTER USER C##USER1
IDENTIFIED BY pw12345;

-- USER1 삭제
DROP USER C##USER1 CASCADE;